project/items/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField
from wtforms.validators import DataRequired, Length


class ItemsForm(FlaskForm):
    name = TextField('Name', validators=[DataRequired(),
                                         Length(min=1, max=254)])
    notes = TextField('Notes')


class EditItemsForm(FlaskForm):
    name = TextField('Name', validators=[DataRequired(),
                                         Length(min=1, max=254)])
    notes = TextField('Notes')

project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo, Email


class RegisterForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),
                                             Email(),
                                             Length(min=6, max=254)])
    password = PasswordField('Password', validators=[DataRequired(),
                                                     Length(min=6, max=254)])
    confirm = PasswordField('Repeat Password',
                            validators=[DataRequired(),
                                        EqualTo('password')])


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),
                                             Email(),
                                             Length(min=6, max=40)])
    password = PasswordField('Password', validators=[DataRequired()])


class EmailForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email(), Length(min=6, max=254)])


class PasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])

project/__init__.py
# IMPORTS
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_login import current_user, login_required
from flask_mail import Mail
import os


# CONFIG
app = Flask(__name__, instance_relative_config=True)
app.config.from_object(os.environ['APP_SETTINGS'])

db = SQLAlchemy(app)
bcrypt = Bcrypt(app)
mail = Mail(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "users.login"

from project.models import User, Items


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


# BLUEPRINTS
from project.users.views import users_blueprint
from project.items.views import items_blueprint

app.register_blueprint(users_blueprint)
app.register_blueprint(items_blueprint)


# ROUTES
@app.route('/', methods=['GET', 'POST'])
@login_required
def home():
    """Render homepage"""

    all_user_items = Items.query.filter_by(user_id=current_user.id)
    return render_template('home.html', items=all_user_items)


# ERROR PAGES
@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@app.errorhandler(403)
def page_forbidden(e):
    return render_template('403.html'), 403


@app.errorhandler(410)
def page_gone(e):
    return render_template('410.html'), 410

project/items/views.py
# project/items/views.py

# IMPORTS
from flask import render_template, Blueprint, request, redirect, url_for, flash, Markup
from flask_login import current_user, login_required
from project import db
from project.models import Items, User
from .forms import ItemsForm, EditItemsForm


# CONFIG
items_blueprint = Blueprint('items', __name__, template_folder='templates')


# ROUTES
@items_blueprint.route('/all_items', methods=['GET', 'POST'])
@login_required
def all_items():
    """Render homepage"""
    all_user_items = Items.query.filter_by(user_id=current_user.id)
    return render_template('all_items.html', items=all_user_items)


@items_blueprint.route('/add_item', methods=['GET', 'POST'])
@login_required
def add_item():
    form = ItemsForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_item = Items(form.name.data, form.notes.data,
                                 current_user.id)
                db.session.add(new_item)
                db.session.commit()
                message = Markup(
                    "<strong>Well done!</strong> Item added successfully!")
                flash(message, 'success')
                return redirect(url_for('home'))
            except:
                db.session.rollback()
                message = Markup(
                    "<strong>Oh snap!</strong>! Unable to add item.")
                flash(message, 'danger')
    return render_template('add_item.html', form=form)


@items_blueprint.route('/edit_item/<items_id>', methods=['GET', 'POST'])
@login_required
def edit_item(items_id):
    form = EditItemsForm(request.form)
    item_with_user = db.session.query(Items, User).join(User).filter(Items.id == items_id).first()
    if item_with_user is not None:
        if current_user.is_authenticated and item_with_user.Items.user_id == current_user.id:
            if request.method == 'POST':
                if form.validate_on_submit():
                    try:
                        item = Items.query.get(items_id)
                        item.name = form.name.data
                        item.notes = form.notes.data
                        db.session.commit()
                        message = Markup("Item edited successfully!")
                        flash(message, 'success')
                        return redirect(url_for('home'))
                    except:
                        db.session.rollback()
                        message = Markup(
                            "<strong>Error!</strong> Unable to edit item.")
                        flash(message, 'danger')
            return render_template('edit_item.html', item=item_with_user, form=form)
        else:
            message = Markup(
                "<strong>Error!</strong> Incorrect permissions to access this item.")
            flash(message, 'danger')
    else:
        message = Markup("<strong>Error!</strong> Item does not exist.")
        flash(message, 'danger')
    return redirect(url_for('home'))


@items_blueprint.route('/delete_item/<items_id>')
@login_required
def delete_item(items_id):
    item = Items.query.filter_by(id=items_id).first_or_404()

    if not item.user_id == current_user.id:
        message = Markup(
            "<strong>Error!</strong> Incorrect permissions to delete this item.")
        flash(message, 'danger')
        return redirect(url_for('home'))

    db.session.delete(item)
    db.session.commit()
    flash('{} was deleted.'.format(item.name), 'success')
    return redirect(url_for('items.all_items'))

project/users/views.py
# project/users/views.py

# IMPORTS
from flask import render_template, Blueprint, request, redirect, url_for, flash, Markup, abort
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from itsdangerous import URLSafeTimedSerializer
from threading import Thread
from flask_mail import Message
from datetime import datetime, timedelta

from .forms import RegisterForm, LoginForm, EmailForm, PasswordForm
from project import app, db, mail
from project.models import User


# CONFIG
users_blueprint = Blueprint('users', __name__, template_folder='templates')


# HELPERS
def send_async_email(msg):
    with app.app_context():
        mail.send(msg)


def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for(
        'users.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'email_confirmation.html',
        confirm_url=confirm_url)

    send_email('Confirm Your Email Address', [user_email], html)


def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    password_reset_url = url_for(
        'users.reset_with_token',
        token=password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
        _external=True)

    html = render_template(
        'email_password_reset.html',
        password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html)


# ROUTES
@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                send_confirmation_email(new_user.email)
                message = Markup(
                    "<strong>Success!</strong> Thanks for registering. Please check your email to confirm your email address.")
                flash(message, 'success')
                return redirect(url_for('home'))
            except IntegrityError:
                db.session.rollback()
                message = Markup(
                    "<strong>Error!</strong> Unable to process registration.")
                flash(message, 'danger')
    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                if user.is_email_confirmed is not True:
                    user.authenticated = True
                    db.session.add(user)
                    db.session.commit()
                    login_user(user)
                    return redirect(url_for('users.resend_email_confirmation'), )
                if user.is_email_confirmed is True:
                    user.authenticated = True
                    user.last_logged_in = user.current_logged_in
                    user.current_logged_in = datetime.now()
                    db.session.add(user)
                    db.session.commit()
                    login_user(user)
                    message = Markup(
                        "<strong>Welcome back!</strong> You are now successfully logged in.")
                    flash(message, 'success')
                    return redirect(url_for('home'))
            else:
                message = Markup(
                    "<strong>Error!</strong> Incorrect login credentials.")
                flash(message, 'danger')
    return render_template('login.html', form=form)


@users_blueprint.route('/user_profile', methods=['GET', 'POST'])
@login_required
def user_profile():
    return render_template('user_profile.html')


@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=3600)
    except:
        message = Markup(
            "The confirmation link is invalid or has expired.")
        flash(message, 'danger')
        return redirect(url_for('users.login'))

    user = User.query.filter_by(email=email).first()

    if user.email_confirmed:
        message = Markup(
            "Account already confirmed. Please login.")
        flash(message, 'info')
    else:
        user.email_confirmed = True
        user.email_confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        message = Markup(
            "Thank you for confirming your email address!")
        flash(message, 'success')

    return redirect(url_for('home'))


@users_blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            message = Markup(
                "Invalid email address!")
            flash(message, 'danger')
            return render_template('password_reset_email.html', form=form)
        if user.email_confirmed:
            send_password_reset_email(user.email)
            message = Markup(
                "Please check your email for a password reset link.")
            flash(message, 'success')
        else:
            message = Markup(
                "Your email address must be confirmed before attempting a password reset.")
            flash(message, 'danger')
        return redirect(url_for('users.login'))

    return render_template('password_reset_email.html', form=form)


@users_blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    except:
        message = Markup(
            "The password reset link is invalid or has expired.")
        flash(message, 'danger')
        return redirect(url_for('users.login'))

    form = PasswordForm()

    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            message = Markup(
                "Invalid email address!")
            flash(message, 'danger')
            return redirect(url_for('users.login'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        message = Markup(
            "Your password has been updated!")
        flash(message, 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_password_with_token.html', form=form, token=token)


@users_blueprint.route('/admin_view_users')
@login_required
def admin_view_users():
    if current_user.role != 'admin':
        abort(403)
    else:
        users = User.query.order_by(User.id).all()
        return render_template('admin_view_users.html', users=users)


@users_blueprint.route('/admin_dashboard')
@login_required
def admin_dashboard():
    if current_user.role != 'admin':
        abort(403)
    else:
        users = User.query.order_by(User.id).all()
        kpi_mau = User.query.filter(User.last_logged_in > (datetime.today() - timedelta(days=30))).count()
        kpi_total_confirmed = User.query.filter_by(email_confirmed=True).count()
        kpi_mau_percentage = (100 / kpi_total_confirmed) * kpi_mau
        return render_template('admin_dashboard.html', users=users, kpi_mau=kpi_mau, kpi_total_confirmed=kpi_total_confirmed, kpi_mau_percentage=kpi_mau_percentage)


@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    message = Markup("<strong>Goodbye!</strong> You are now logged out.")
    flash(message, 'info')
    return redirect(url_for('users.login'))


@users_blueprint.route('/password_change', methods=["GET", "POST"])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            message = Markup(
                "Password has been updated!")
            flash(message, 'success')
            return redirect(url_for('users.user_profile'))

    return render_template('password_change.html', form=form)


@users_blueprint.route('/resend_confirmation')
@login_required
def resend_email_confirmation():
    try:
        send_confirmation_email(current_user.email)
        message = Markup(
            "Email sent to confirm your email address. Please check your inbox!")
        flash(message, 'success')
        user = current_user
        user.authenticated = False
        db.session.add(user)
        db.session.commit()
        logout_user()
    except IntegrityError:
        message = Markup(
            "Error!  Unable to send email to confirm your email address.")
        flash(message, 'danger')
        user = current_user
        user.authenticated = False
        db.session.add(user)
        db.session.commit()
        logout_user()

project/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="static/css/core.min.css" rel="stylesheet">
    <link href="static/css/thesaas.min.css" rel="stylesheet">
    <link href="static/css/style.css" rel="stylesheet">
  </head>
  <body>
    <!--<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('home') }}">
          <img src="{{ url_for('static', filename='images/favicon.png') }}" width="30" height="30" class="d-inline-block align-top" alt="Flask App Blueprint">
          Flask App Blueprint
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if current_user.is_authenticated %}
          <li class="nav-item {% if request.path == url_for('home') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('home') }}">Home</a>
          </li>
          <li class="nav-item {% if request.path == url_for('items.all_items') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('items.all_items') }}">All Items</a>
          </li>
          <li class="nav-item {% if request.path == url_for('items.add_item') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('items.add_item') }}">Add Items</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{current_user.email}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('users.user_profile') }}">My Profile</a>
              {% if current_user.role == "admin" %}
              <a class="dropdown-item" href="{{ url_for('users.admin_dashboard') }}">Admin Dashboard</a>
              {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ url_for('users.logout') }}">Log Out</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item {% if request.path == url_for('users.register') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
          </li>
          <li class="nav-item {% if request.path == url_for('users.login') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('users.login') }}">Log In</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>-->


    <div class="container mt-4">
      {% for primary_message in get_flashed_messages(category_filter=["primary"]) %}
      <div class="alert alert-primary alert-dismissible fade show" role="alert">
        {{ primary_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% for secondary_message in get_flashed_messages(category_filter=["secondary"]) %}
      <div class="alert alert-secondary alert-dismissible fade show" role="alert">
        {{ secondary_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% for success_message in get_flashed_messages(category_filter=["success"]) %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ success_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% for danger_message in get_flashed_messages(category_filter=["danger"]) %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ danger_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% for warning_message in get_flashed_messages(category_filter=["warning"]) %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ warning_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% for info_message in get_flashed_messages(category_filter=["info"]) %}
      <div class="alert alert-info alert-dismissible fade show" role="alert">
        {{ info_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
    </div>

    <div class="container">
      <div class="mt-5">
        <h1>{{ self.title() }}</h1>
        <hr>
      </div>
      {% block content %}{% endblock %}
    </div>

    <footer>
        <footer class="site-footer">
            <div class="container">
              <div class="row gap-y align-items-center">
                <div class="col-12 col-lg-3">
                  <p class="text-center text-lg-left">
                    <a href="index.html"><img src="static/img/logo.png" alt="logo"></a>
                  </p>
                </div>
      
                <div class="col-12 col-lg-6">
                  <ul class="nav nav-primary nav-hero">
                    <li class="nav-item">
                      <a class="nav-link" href="index.html">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="blog.html">Blog</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="block-feature.html">Features</a>
                    </li>
                    <li class="nav-item hidden-sm-down">
                      <a class="nav-link" href="page-pricing.html">Pricing</a>
                    </li>
                    <li class="nav-item hidden-sm-down">
                      <a class="nav-link" href="page-contact.html">Contact</a>
                    </li>
                  </ul>
                </div>
      
                <div class="col-12 col-lg-3">
                  <div class="social text-center text-lg-right">
                    <a class="social-facebook" href="https://www.facebook.com/thethemeio"><i class="fa fa-facebook"></i></a>
                    <a class="social-twitter" href="https://twitter.com/thethemeio"><i class="fa fa-twitter"></i></a>
                    <a class="social-instagram" href="https://www.instagram.com/thethemeio/"><i class="fa fa-instagram"></i></a>
                    <a class="social-dribbble" href="https://dribbble.com/thethemeio"><i class="fa fa-dribbble"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </footer>
      <!-- <div class="container" style="margin-top:250px">
        <ul class="nav justify-content-center">
          <li class="nav-item"><a class="nav-link active" href="#">About</a></li>
          <li class="nav-item"><a class="nav-link active" href="#">FAQ</a></li>
          <li class="nav-item"><a class="nav-link active" href="#">Contact / Feedback</a></li>
        </ul>
        <p class="text-center"><a href="https://github.com/jelmerdejong/flask-app-blueprint">Created by Flask App Blueprint.</a></p>
      </div> -->
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

project/templates/add_item.html
{% extends "_base.html" %}
{% block title %}Add Item{% endblock %}
{% from "_formshelper.html" import render_field %}
{% block content %}

<div class="row">
  <div class="col-md-6">
    <form action="{{ url_for('items.add_item') }}" method="post" name="itemsform">
        {{ form.csrf_token }}
        <div class="form-group">
          {{ form.name.label }}
          {{ render_field(form.name, class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.notes.label }}
          {{ render_field(form.notes, class="form-control") }}
        </div>
        <input type="submit" value="Add Item" class="btn btn-lg btn-success">
    </form>
  </div>
  <div class="col-md-6">
    <h4>On adding items</h4>
    <p>If you need hep, provide it here.</p>
  </div>
</div>

{% endblock %}

project/templates/all_items.html
{% extends "_base.html" %}
{% block title %}All Items{% endblock %}
{% block content %}

{% if items[0] == NULL %}
<div class="panel-body">
  <p>No items are added yet, <a href="{{ url_for('items.add_item') }}">add a new item</a>.</p>
</div>
{% else %}
<table class="table table-stripe">
  <thead>
    <tr>
      <th class="border-top-0">Name</th>
      <th class="border-top-0">Notes</th>
      <th class="border-top-0"></th>
    </tr>
  </thead>
  <tbody>
    {% for item in items %}
    <tr>
      <td>{{ item.name }}</td>
      <td>
        {{ item.notes }}
      </td>
      <td>
        <a href="{{ url_for('items.edit_item', items_id=item.id) }}">Edit</a>
        <a href="{{ url_for('items.delete_item', items_id=item.id) }}">Delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

{% endblock %}

project/templates/delete_item.html
{% extends "_base.html" %}
{% block title %}Delete Item{% endblock %}
{% block content %}

<form action="{{ url_for('items.delete_item', items_id=items[0].id) }}" method="post" name="deleteitemsform">
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="border-top-0">Name</th>
            <th class="border-top-0">Notes</th>
          </tr>
        </thead>
        <tbody>
          {% for item in items %}
          <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.notes }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    <input type="submit" value="Delete Item" class="btn btn-lg btn-success">
</form>

{% endblock %}

project/templates/edit_item.html
{% extends "_base.html" %}
{% block title %}Edit Item{% endblock %}
{% from "_formshelper.html" import render_field %}
{% block content %}

<form action="{{ url_for('items.edit_item', items_id=item.Items.id) }}" method="post" name="edititemsform">
    {{ form.csrf_token }}
    <div class="form-group">
      {{ form.name.label }}
      {{ render_field(form.name, class="form-control", value=item.Items.name) }}
    </div>
    <div class="form-group">
      {{ form.notes.label }}
      {{ render_field(form.notes, class="form-control", value=item.Items.notes) }}
    </div>
    <input type="submit" value="Edit Item" class="btn btn-lg btn-success">
</form>

{% endblock %}

project/templates/home.html
{% extends "_base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}

<div class="card">
  <div class="card-body">
    <h4 class="card-title">My Items</h4>
    {% if items[0] == NULL %}
    <p class="card-text">No items are added yet, <a href="{{ url_for('items.add_item') }}">add a new item</a>.</p>
    {% else %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <tr>
          <td>{{ item.name }}</td>
          <td>{{ item.notes }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>

{% endblock %}

project/templates/password_change.html
{% extends "_base.html" %}
{% block title %}Change Password{% endblock %}
{% from "_formshelper.html" import render_field %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    <form action="{{ url_for('users.user_password_change') }}" method="post">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.password.label }}
        {{ render_field(form.password, placeholder="Enter New Password", class="form-control") }}
      </div>
      <input type="submit" value="Change Password" class="btn btn-lg btn-success">
    </form>
  </div>
</div>

{% endblock %}

project/templates/register.html
{% extends "_base.html" %}
{% block title %}Get started with a free account{% endblock %}
{% from "_formshelper.html" import render_field %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    <form action="{{ url_for('users.register') }}" method="post">
        {{ form.csrf_token }}
        <div class="form-group">
          {{ form.email.label }}
          {{ render_field(form.email, class="form-control", placeholder="Email address") }}
        </div>
        <div class="form-group">
          {{ form.password.label }}
          {{ render_field(form.password, class="form-control", placeholder="Password") }}
        </div>
        <div class="form-group">
          {{ form.confirm.label }}
          {{ render_field(form.confirm, class="form-control", placeholder="Confirm password") }}
        </div>
        <input type="submit" value="Get Started!" class="btn btn-lg btn-success">
    </form>
  </div>
  <div class="col-md-6">
    <h3>Start your new MVP today!</h3>
    <h4>Flask App Blueprint: focus on your unique idea.</h4>
    <p>With Flask App Blueprint you have a simple to start direclty with your idea, without spending way to much time fixing the basics. Get going, start today.</p>
    <p>
      <ul>
        <li>Powerful technology stack (Python, Postgress, Flask, Bootstrap, and more).</li>
        <li>Directly able to go live by deploying to Heroku.</li>
        <li>Register, Login, CRUD to database, public and private posts.</li>
      </ul>
    </p>
    <p></p>
  </div>
</div>

{% endblock %}